services:
  api:
    build:
      context: .
      dockerfile: ClientManager.API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ./ClientManager.Infrastructure/DataStorage:/app/Data

  client:
    build:
      context: .
      dockerfile: ClientManager.Client/Dockerfile
    ports:
      - "5003:80"